Predict the different species of flowers on
the length of there petals and sepals
only Jupyter notebook code.

In [1]:
from sklearn import datasets

C:\Users\Krishnarpit\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [4]:
# Print Target Name and Feature Name
print(iris.target_names)
print(iris.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [5]:
import pandas as pd
data=pd.DataFrame({"sepal length(cm)":iris.data[:,0],'sepal width (cm)':iris.data[:,1], 'petal length (cm)':iris.data[:,2], 
              'petal width (cm)':iris.data[:,3],'species':iris.target})

In [6]:
data

,sepal length(cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [7]:
data.head()

,sepal length(cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [8]:
x = data[['sepal length(cm)','sepal width (cm)','petal length (cm)','petal width (cm)']] # Features
y = data['species']

In [9]:
x

     sepal length(cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
145               6.7               3.0                5.2               2.3
146               6.3               2.5                5.0               1.9
147               6.5               3.0                5.2               2.0
148               6.2               3.4                5.4               2.3
149               5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [13]:
x_train

     sepal length(cm)  sepal width (cm)  petal length (cm)  petal width (cm)
124               6.7               3.3                5.7               2.1
55                5.7               2.8                4.5               1.3
62                6.0               2.2                4.0               1.0
141               6.9               3.1                5.1               2.3
91                6.1               3.0                4.6               1.4
..                ...               ...                ...               ...
15                5.7               4.4                1.5               0.4
35                5.0               3.2                1.2               0.2
87                6.3               2.3                4.4               1.3
34                4.9               3.1                1.5               0.2
3                 4.6               3.1                1.5               0.2

[105 rows x 4 columns]

In [14]:
x_test

     sepal length(cm)  sepal width (cm)  petal length (cm)  petal width (cm)
144               6.7               3.3                5.7               2.5
23                5.1               3.3                1.7               0.5
103               6.3               2.9                5.6               1.8
78                6.0               2.9                4.5               1.5
39                5.1               3.4                1.5               0.2
48                5.3               3.7                1.5               0.2
6                 4.6               3.4                1.4               0.3
54                6.5               2.8                4.6               1.5
72                6.3               2.5                4.9               1.5
38                4.4               3.0                1.3               0.2
2                 4.7               3.2                1.3               0.2
24                4.8               3.4                1.9               0.2
104               6.5               3.0                5.8               2.2
85                6.0               3.4                4.5               1.6
123               6.3               2.7                4.9               1.8
98                5.1               2.5                3.0               1.1
90                5.5               2.6                4.4               1.2
132               6.4               2.8                5.6               2.2
4                 5.0               3.6                1.4               0.2
83                6.0               2.7                5.1               1.6
129               7.2               3.0                5.8               1.6
80                5.5               2.4                3.8               1.1
116               6.5               3.0                5.5               1.8
26                5.0               3.4                1.6               0.4
105               7.6               3.0                6.6               2.1
30                4.8               3.1                1.6               0.2
71                6.1               2.8                4.0               1.3
88                5.6               3.0                4.1               1.3
94                5.6               2.7                4.2               1.3
16                5.4               3.9                1.3               0.4
69                5.6               2.5                3.9               1.1
143               6.8               3.2                5.9               2.3
76                6.8               2.8                4.8               1.4
46                5.1               3.8                1.6               0.2
43                5.0               3.5                1.6               0.6
21                5.1               3.7                1.5               0.4
101               5.8               2.7                5.1               1.9
109               7.2               3.6                6.1               2.5
110               6.5               3.2                5.1               2.0
100               6.3               3.3                6.0               2.5
42                4.4               3.2                1.3               0.2
7                 5.0               3.4                1.5               0.2
108               6.7               2.5                5.8               1.8
122               7.7               2.8                6.7               2.0
128               6.4               2.8                5.6               2.1

In [15]:
y_train

124    2
55     1
62     1
141    2
91     1
      ..
15     0
35     0
87     1
34     0
3      0
Name: species, Length: 105, dtype: int32

In [16]:
y_test

144    2
23     0
103    2
78     1
39     0
48     0
6      0
54     1
72     1
38     0
2      0
24     0
104    2
85     1
123    2
98     1
90     1
132    2
4      0
83     1
129    2
80     1
116    2
26     0
105    2
30     0
71     1
88     1
94     1
16     0
69     1
143    2
76     1
46     0
43     0
21     0
101    2
109    2
110    2
100    2
42     0
7      0
108    2
122    2
128    2
Name: species, dtype: int32

In [17]:
len(x_train)

105

In [18]:
len(y_train)

105

In [19]:
len(x_test)

45

In [20]:
len(y_test)

45

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
clf = RandomForestClassifier(n_estimators=100,criterion='gini')

In [23]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [24]:
 # 0 'setosa' , 1 'versicolor  , 2 'virginica'[prediction]
clf.predict(x_test)

array([2, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 2, 1,
       2, 0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 2, 2, 2, 2, 0, 0, 2, 2,
       2])

In [25]:
x_test

     sepal length(cm)  sepal width (cm)  petal length (cm)  petal width (cm)
144               6.7               3.3                5.7               2.5
23                5.1               3.3                1.7               0.5
103               6.3               2.9                5.6               1.8
78                6.0               2.9                4.5               1.5
39                5.1               3.4                1.5               0.2
48                5.3               3.7                1.5               0.2
6                 4.6               3.4                1.4               0.3
54                6.5               2.8                4.6               1.5
72                6.3               2.5                4.9               1.5
38                4.4               3.0                1.3               0.2
2                 4.7               3.2                1.3               0.2
24                4.8               3.4                1.9               0.2
104               6.5               3.0                5.8               2.2
85                6.0               3.4                4.5               1.6
123               6.3               2.7                4.9               1.8
98                5.1               2.5                3.0               1.1
90                5.5               2.6                4.4               1.2
132               6.4               2.8                5.6               2.2
4                 5.0               3.6                1.4               0.2
83                6.0               2.7                5.1               1.6
129               7.2               3.0                5.8               1.6
80                5.5               2.4                3.8               1.1
116               6.5               3.0                5.5               1.8
26                5.0               3.4                1.6               0.4
105               7.6               3.0                6.6               2.1
30                4.8               3.1                1.6               0.2
71                6.1               2.8                4.0               1.3
88                5.6               3.0                4.1               1.3
94                5.6               2.7                4.2               1.3
16                5.4               3.9                1.3               0.4
69                5.6               2.5                3.9               1.1
143               6.8               3.2                5.9               2.3
76                6.8               2.8                4.8               1.4
46                5.1               3.8                1.6               0.2
43                5.0               3.5                1.6               0.6
21                5.1               3.7                1.5               0.4
101               5.8               2.7                5.1               1.9
109               7.2               3.6                6.1               2.5
110               6.5               3.2                5.1               2.0
100               6.3               3.3                6.0               2.5
42                4.4               3.2                1.3               0.2
7                 5.0               3.4                1.5               0.2
108               6.7               2.5                5.8               1.8
122               7.7               2.8                6.7               2.0
128               6.4               2.8                5.6               2.1

In [26]:
# score
clf.score(x_test,y_test)

0.9555555555555556

In [27]:
# prediction
clf.predict([[3,5,4,2]])

C:\Users\Krishnarpit\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [28]:
# Important & less important features
pd.Series(clf.feature_importances_,index=iris.feature_names).sort_values(ascending=False)

petal length (cm)    0.489351
petal width (cm)     0.381244
sepal length (cm)    0.102612
sepal width (cm)     0.026793
dtype: float64

In [29]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [30]:
feature_imp = pd.Series(clf.feature_importances_,index=iris.feature_names).sort_values(ascending=False)

In [31]:
feature_imp

petal length (cm)    0.489351
petal width (cm)     0.381244
sepal length (cm)    0.102612
sepal width (cm)     0.026793
dtype: float64

In [32]:
# Remove less important features
x = data[['petal length (cm)','petal width (cm)','sepal length(cm)']]
y = data['species']

In [33]:
x

     petal length (cm)  petal width (cm)  sepal length(cm)
0                  1.4               0.2               5.1
1                  1.4               0.2               4.9
2                  1.3               0.2               4.7
3                  1.5               0.2               4.6
4                  1.4               0.2               5.0
..                 ...               ...               ...
145                5.2               2.3               6.7
146                5.0               1.9               6.3
147                5.2               2.0               6.5
148                5.4               2.3               6.2
149                5.1               1.8               5.9

[150 rows x 3 columns]

In [34]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [35]:
# Split The Data
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [37]:
x_train

     petal length (cm)  petal width (cm)  sepal length(cm)
73                 4.7               1.2               6.1
142                5.1               1.9               5.8
126                4.8               1.8               6.2
101                5.1               1.9               5.8
145                5.2               2.3               6.7
..                 ...               ...               ...
127                4.9               1.8               6.1
48                 1.5               0.2               5.3
87                 4.4               1.3               6.3
37                 1.4               0.1               4.9
32                 1.5               0.1               5.2

[105 rows x 3 columns]

In [38]:
x_test

     petal length (cm)  petal width (cm)  sepal length(cm)
66                 4.5               1.5               5.6
103                5.6               1.8               6.3
62                 4.0               1.0               6.0
138                4.8               1.8               6.0
107                6.3               1.8               7.3
12                 1.4               0.1               4.8
47                 1.4               0.2               4.6
4                  1.4               0.2               5.0
147                5.2               2.0               6.5
108                5.8               1.8               6.7
17                 1.4               0.3               5.1
38                 1.3               0.2               4.4
81                 3.7               1.0               5.5
140                5.6               2.4               6.7
20                 1.7               0.2               5.4
25                 1.6               0.2               5.0
0                  1.4               0.2               5.1
109                6.1               2.5               7.2
123                4.9               1.8               6.3
16                 1.3               0.4               5.4
120                5.7               2.3               6.9
30                 1.6               0.2               4.8
33                 1.4               0.2               5.5
85                 4.5               1.6               6.0
10                 1.5               0.2               5.4
27                 1.5               0.2               5.2
14                 1.2               0.2               5.8
65                 4.4               1.4               6.7
149                5.1               1.8               5.9
94                 4.2               1.3               5.6
46                 1.6               0.2               5.1
128                5.6               2.1               6.4
95                 4.2               1.2               5.7
52                 4.9               1.5               6.9
111                5.3               1.9               6.4
19                 1.5               0.3               5.1
34                 1.5               0.2               4.9
49                 1.4               0.2               5.0
26                 1.6               0.4               5.0
91                 4.6               1.4               6.1
76                 4.8               1.4               6.8
43                 1.6               0.6               5.0
42                 1.3               0.2               4.4
77                 5.0               1.7               6.7
119                5.0               1.5               6.0

In [39]:
y_train

73     1
142    2
126    2
101    2
145    2
      ..
127    2
48     0
87     1
37     0
32     0
Name: species, Length: 105, dtype: int32

In [40]:
y_test

66     1
103    2
62     1
138    2
107    2
12     0
47     0
4      0
147    2
108    2
17     0
38     0
81     1
140    2
20     0
25     0
0      0
109    2
123    2
16     0
120    2
30     0
33     0
85     1
10     0
27     0
14     0
65     1
149    2
94     1
46     0
128    2
95     1
52     1
111    2
19     0
34     0
49     0
26     0
91     1
76     1
43     0
42     0
77     1
119    2
Name: species, dtype: int32

In [43]:
# Import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [44]:
clr1=RandomForestClassifier()

In [45]:
# Train The Model
clr1.fit(x_train,y_train)

RandomForestClassifier()

In [46]:
# Predict 
clr1.predict(x_test)

array([1, 2, 1, 1, 2, 0, 0, 0, 2, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0,
       0, 1, 0, 0, 0, 1, 2, 1, 0, 2, 1, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 2,
       1])

In [47]:
clr1.score(x_test,y_test)

0.9333333333333333